[project]
name = "mcpath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    { name = "BEN", email = "toussaint.benoit@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mcpath = "mcpath:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "bashlex>=0.18",
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]
